Repository Team-5-CodeCat/otto-front, pull requests merged in 2025-09, with the labels that each got.

#11 refactor: change route structure
  .gitignore
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/(dashboard)/pipelines/components/CustomEdge.tsx
  app/(dashboard)/pipelines/components/CustomNode.tsx
  app/(dashboard)/pipelines/components/NodeStatusIndicator.tsx
  app/(dashboard)/pipelines/components/index.ts
  app/(dashboard)/projects/components/EnvPopup.tsx
  app/(dashboard)/projects/components/index.ts
  app/(landing)/landing.tsx
  app/(landing)/privacy/page.tsx
  app/(landing)/terms/page.tsx
  app/components/Sidebar.tsx
  app/flow/FlowEditor.tsx
  app/flow/OutputPanel.tsx
  app/flow/ScriptEditor.tsx
  app/flow/codegen.ts
  app/flow/scriptParser.ts
  app/layout.tsx
  app/page.tsx
  app/workspace/layout.tsx
  app/workspace/page.tsx
  components/icons.tsx
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  tailwind.config.ts
  tools/github/types.ts
Labels: refactor

#14 feat: sdk 통합
  .npmrc
  app/(auth)/signin/page.tsx
  app/hooks/useAuth.ts
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#17 feat: 간선오류 수정
  app/(dashboard)/pipelines/components/FlowCanvas.tsx
  app/(dashboard)/pipelines/components/JobNode.tsx
  app/(dashboard)/pipelines/components/NodePalette.tsx
  app/(dashboard)/pipelines/components/RightPanel.tsx
  app/(dashboard)/pipelines/components/types.ts
  app/(dashboard)/pipelines/components/usePipeline.ts
  app/(dashboard)/pipelines/components/utils.ts
  app/(dashboard)/pipelines/page.tsx
Labels: bug

#18 chore: sdk 버전 수정
  package.json
  pnpm-lock.yaml
Labels: refactor

#23 add: .env 탭 수정
  app/(dashboard)/builds/[id]/page.tsx
  app/(dashboard)/builds/page.tsx
  app/(dashboard)/environments/page.tsx
  app/(dashboard)/pipelines/components/RightPanel.tsx
  app/(dashboard)/pipelines/components/usePipeline.ts
  app/(dashboard)/projects/[id]/edit/page.tsx
  app/(dashboard)/projects/[id]/page.tsx
  app/(dashboard)/projects/components/EnvPopup.tsx
  app/(dashboard)/projects/components/index.ts
  app/(dashboard)/projects/new/page.tsx
  app/(dashboard)/projects/page.tsx
  app/(dashboard)/tests/[id]/page.tsx
  app/(dashboard)/tests/page.tsx
  app/components/dashboard/DashboardLayout.tsx
  app/components/dashboard/Sidebar.tsx
  app/components/ui/EnvFileUploader.tsx
  app/components/ui/EnvironmentTab.tsx
  app/components/ui/EnvironmentVariableList.tsx
  app/components/ui/YamlEditor.tsx
  app/contexts/NodeVersionContext.tsx
Labels: enhancement

#24 fix: 레이아웃 수정
  app/(dashboard)/pipelines/components/FlowCanvas.tsx
  app/(dashboard)/pipelines/components/NodePalette.tsx
  app/(dashboard)/pipelines/page.tsx
  app/components/dashboard/ActionIcons.tsx
  app/components/dashboard/DashboardLayout.tsx
  app/components/dashboard/DropdownSelect.tsx
  app/components/dashboard/PipelineBuilder.tsx
  app/components/dashboard/Sidebar.tsx
  app/components/dashboard/constants.ts
  app/components/dashboard/types.ts
  app/lib/uiStore.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#32 feat: run 클릭시 파이프라인 실행
  app/(dashboard)/pipelines/components/FlowCanvas.tsx
  app/(dashboard)/pipelines/components/LoadPipelineModal.tsx
  app/(dashboard)/pipelines/components/RightPanel.tsx
  app/(dashboard)/pipelines/components/SavePipelineModal.tsx
  app/(dashboard)/pipelines/page.tsx
  app/(dashboard)/projects/new/page.tsx
  package.json
  pnpm-lock.yaml
Labels: enhancement

#33 fix: sdk 경로 소문자->대문자 변경
  app/(dashboard)/pipelines/page.tsx
  app/(dashboard)/projects/new/page.tsx
Labels: enhancement

#35 fix: 파이프라인 화면 영어 수정
  app/(dashboard)/pipelines/components/usePipeline.ts
  app/(dashboard)/pipelines/components/utils.ts
  app/components/dashboard/constants.ts
  app/components/ui/NodeVersionSelector.tsx
Labels: enhancement

#37 fix: 로그 화면 영어로 변경
  app/(dashboard)/builds/page.tsx
Labels: enhancement

#38 fix: ui/ux개선
  app/(dashboard)/pipelines/components/CustomEdge.tsx
  app/(dashboard)/pipelines/components/FlowCanvas.tsx
  app/(dashboard)/pipelines/components/JobNode.tsx
  app/(dashboard)/pipelines/components/RightPanel.tsx
  app/(dashboard)/pipelines/page.tsx
  app/components/dashboard/Sidebar.tsx
  app/components/ui/EnvironmentTab.tsx
  app/components/ui/EnvironmentVariableList.tsx
  app/components/ui/NodeVersionSelector.tsx
Labels: enhancement

#41 feat: 에러메세지 수정
  app/lib/error-messages.ts
Labels: enhancement

#43 fix: infinite rerender
  app/lib/uiStore.ts
Labels: bug
